version: '3.3'
services:
  web:
    build:
      context: ./php
    container_name: php73
    depends_on:
      - db
    volumes:
      - ./public_html:/var/www/html
    ports:
      - 8000:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schoolbase
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 6033:3306
    volumes:
      - data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 30002:80
    environment:
      - PMA_HOST=mysql8
      - PMA_PORT= 3306
volumes:
    data:
 
